language: ruby

notifications:
  email:
    - didyourupgradeclear@gmail.com

rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - ruby-head
  - jruby-head

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
